project: content-manager
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/demoo-ooclock
        keys:
          content_manager_service_account: GOOGLE_SERVICE_ACCOUNT_JSON
          microblog-content-manager: MICROBLOG_APP_TOKEN
          marsedit_token: MICROBLOG_XMLRPC_TOKEN
          bluesky_password: BLUESKY_PASSWORD
          LinkedIn_Client_ID: LINKEDIN_CLIENT_ID
          LinkedIn_Client_Secret: LINKEDIN_CLIENT_SECRET
          linkedin_access_token: LINKEDIN_ACCESS_TOKEN
          linkedin_token_expires_at: LINKEDIN_TOKEN_EXPIRES_AT
          linkedin_person_urn: LINKEDIN_PERSON_URN
