name: Sync Content to Micro.blog

on:
  # Manual trigger for testing
  workflow_dispatch:

  # Scheduled run (daily at 10:30am US Central)
  schedule:
    - cron: '30 15 * * *'  # Run at 3:30pm UTC = 10:30am Central (CDT) / 9:30am Central (CST)

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    concurrency:
      group: sync-content-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Run content sync
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          MICROBLOG_APP_TOKEN: ${{ secrets.MICROBLOG_APP_TOKEN }}
          MICROBLOG_XMLRPC_TOKEN: ${{ secrets.MICROBLOG_XMLRPC_TOKEN }}
          MICROBLOG_USERNAME: ${{ secrets.MICROBLOG_USERNAME }}
        run: node src/sync-content.js
