name: Update Page Visibility

on:
  # Manual trigger for testing
  workflow_dispatch:

  # Scheduled run (daily at 3 AM UTC)
  schedule:
    - cron: '0 3 * * *'  # Run at 3 AM UTC every day

jobs:
  update-visibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Update page visibility
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          MICROBLOG_XMLRPC_TOKEN: ${{ secrets.MICROBLOG_XMLRPC_TOKEN }}
          MICROBLOG_USERNAME: ${{ secrets.MICROBLOG_USERNAME }}
        run: node src/update-page-visibility.js
